# Generated by Django 4.2.7 on 2023-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_modeldrivingbridge_modelengine_modelsteeredbridge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelequipment',
            name='description',
            field=models.CharField(blank=True, default='Описание техники', max_length=512),
        ),
    ]
