# Generated by Django 4.2.7 on 2023-11-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_clientuser_name_company'),
        ('manuals', '0002_modeldrivingbridge_modelengine_modelsteeredbridge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_technique', models.IntegerField(unique=True)),
                ('serial_number_engine', models.CharField(max_length=32, unique=True)),
                ('serial_number_transmission', models.CharField(max_length=32, unique=True)),
                ('serial_number_driving_bridge', models.CharField(max_length=32, unique=True)),
                ('serial_number_steered_bridge', models.CharField(max_length=32, unique=True)),
                ('shipment_date', models.DateField()),
                ('supply_contract', models.CharField(blank=True, max_length=128)),
                ('consignee', models.CharField(max_length=128)),
                ('delivery_address', models.CharField(max_length=256)),
                ('equipment', models.TextField(max_length=5000)),
                ('customer', models.ForeignKey(limit_choices_to={'status': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.clientuser')),
                ('model_driving_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.modeldrivingbridge')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.modelengine')),
                ('model_steered_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.modelsteeredbridge')),
                ('model_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.modelequipment')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.modeltransmission')),
                ('service_company', models.ForeignKey(limit_choices_to={'status': 'SERVICE'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.clientuser')),
            ],
        ),
    ]
