# Generated by Django 4.2.7 on 2023-11-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial_number_technique',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
