# Generated by Django 4.2.7 on 2023-11-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientuser_name_company'),
        ('cars', '0003_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'status': 'SERVICE'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='accounts.clientuser'),
        ),
    ]
