# Generated by Django 4.2.7 on 2023-12-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_modeldrivingbridge_modelengine_modelsteeredbridge_and_more'),
        ('accounts', '0003_alter_clientuser_name_company'),
        ('cars', '0005_alter_maintenance_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_time', models.IntegerField()),
                ('description_failure', models.TextField(max_length=2048)),
                ('spares', models.TextField(blank=True, max_length=1024)),
                ('restore_date', models.DateField(blank=True)),
                ('downtime', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.machine')),
                ('node_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.nodefailure')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.recoverymethod')),
                ('service_company', models.ForeignKey(limit_choices_to={'status': 'SERVICE'}, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.clientuser')),
            ],
        ),
    ]
