# Generated by Django 4.2.7 on 2023-12-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='service_company',
        ),
    ]
