# Generated by Django 4.2.7 on 2023-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_claim_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='restore_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
