# Generated by Django 4.2.7 on 2023-12-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_claim_downtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-shipment_date']},
        ),
    ]
