# Generated by Django 4.2.7 on 2023-12-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_machine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-service_date']},
        ),
    ]
