# Generated by Django 4.2.7 on 2023-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientuser_name_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='name_company',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
